### ISSUE TITLE
Update Ketcher feedback information on Ketcher page

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/lifescience#75]
Please, update the Feedback links that should be presented on the Ketcher page in the Feedback section. Right now the obsolete Google Groups links are presented. Use Ketcher Github and EPAM Solutions links instead.

Page: https://lifescience.opensource.epam.com/ketcher/index.html

The section that should be fixed:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/90251323/148912858-530ff35c-0f5c-41e3-9e49-d7746f338342.png">

**Comment by AlexanderSavelyev** [comment]
close since no longer an issue
