### ISSUE TITLE
Update Ketcher demo to new release version 2.4.0

### ISSUE THREAD

**Issue by SunFellow** [epam/lifescience#78]
Currently Ketcher Demo page offers demos with Ketcher version 2.3.1 based on Indigo 1.3.0beta (remote) and Indigo 1.4.3 (Standalone).

It's time to update the demos to recently released versions Ketcher 2.4.0 + Indigo 1.6.1.

![Ketcher 2 3 Remote](https://user-images.githubusercontent.com/58183229/150651048-5a4ac0b0-cda8-4c1a-b5ff-0331ef4a4ac0.png)

![Ketcher 2 3 Standalone](https://user-images.githubusercontent.com/58183229/150651151-a8f4d6b7-3b63-4057-85f4-f1c256139426.png)

**Comment by AlexanderSavelyev** [comment]
latest ketcher demo was updated to latest 2.5.0
